# Generated by Django 6.0.6 on 2026-06-27 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='企业名称')),
                ('credit_code', models.CharField(max_length=50, unique=True, verbose_name='统一社会信用代码')),
                ('legal_person', models.CharField(max_length=50, verbose_name='法定代表人')),
                ('legal_person_id', models.CharField(blank=True, max_length=30, verbose_name='法定代表人身份证号')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('company_address', models.TextField(verbose_name='企业地址')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='licenses/', verbose_name='营业执照')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已认证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '企业档案',
                'verbose_name_plural': '企业档案',
            },
        ),
        migrations.CreateModel(
            name='TransferApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(blank=True, max_length=30, unique=True, verbose_name='申请编号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交待审核'), ('under_review', '审核中'), ('changes_requested', '需修改'), ('approved', '审核通过'), ('rejected', '审核不通过'), ('completed', '已完成备案')], default='draft', max_length=20, verbose_name='状态')),
                ('waste_name', models.CharField(max_length=200, verbose_name='废物名称')),
                ('waste_code', models.CharField(max_length=50, verbose_name='废物代码')),
                ('waste_category', models.CharField(blank=True, max_length=100, verbose_name='废物类别')),
                ('waste_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='转移数量')),
                ('waste_unit', models.CharField(default='吨', max_length=20, verbose_name='计量单位')),
                ('waste_physical_state', models.CharField(blank=True, max_length=50, verbose_name='物理状态')),
                ('waste_description', models.TextField(blank=True, verbose_name='废物描述')),
                ('source_address', models.TextField(verbose_name='产废地址')),
                ('source_contact', models.CharField(max_length=50, verbose_name='产废单位联系人')),
                ('source_phone', models.CharField(max_length=20, verbose_name='产废单位电话')),
                ('transport_start_date', models.DateField(verbose_name='计划转移开始日期')),
                ('transport_end_date', models.DateField(verbose_name='计划转移结束日期')),
                ('receiving_company', models.CharField(max_length=200, verbose_name='接收单位名称')),
                ('receiving_address', models.TextField(verbose_name='接收单位地址')),
                ('receiving_legal_person', models.CharField(max_length=50, verbose_name='接收单位法定代表人')),
                ('receiving_contact', models.CharField(max_length=50, verbose_name='接收单位联系人')),
                ('receiving_phone', models.CharField(max_length=20, verbose_name='接收单位电话')),
                ('transport_company', models.CharField(max_length=200, verbose_name='运输单位名称')),
                ('transport_address', models.TextField(blank=True, verbose_name='运输单位地址')),
                ('transport_contact', models.CharField(blank=True, max_length=50, verbose_name='运输单位联系人')),
                ('transport_phone', models.CharField(blank=True, max_length=20, verbose_name='运输单位电话')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approval_notice', models.FileField(blank=True, null=True, upload_to='notices/', verbose_name='跨省转出通报文件')),
                ('approval_notice_name', models.CharField(blank=True, max_length=200, verbose_name='通报文件名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申请企业')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '转移申请',
                'verbose_name_plural': '转移申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', '提交申请'), ('approve', '审核通过'), ('reject', '审核不通过'), ('request_changes', '退回修改'), ('issue_notice', '签发通报')], max_length=20, verbose_name='操作')),
                ('comment', models.TextField(blank=True, verbose_name='意见说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='gufei_beian.transferapplication', verbose_name='申请')),
            ],
            options={
                'verbose_name': '审核日志',
                'verbose_name_plural': '审核日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('contract', '委托合同'), ('receiver_qualification', '接收方资质'), ('transporter_qualification', '运输方资质'), ('legal_person_id', '法人身份证明'), ('authorization_letter', '授权委托书'), ('approval_notice', '备案通报文件')], max_length=30, verbose_name='文档类型')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='文件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gufei_beian.transferapplication', verbose_name='所属申请')),
            ],
            options={
                'verbose_name': '申请材料',
                'verbose_name_plural': '申请材料',
            },
        ),
    ]
