# Generated by Django 6.0.6 on 2026-06-29 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gufei_beian', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpriseprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reviewlog',
            name='application',
        ),
        migrations.RemoveField(
            model_name='reviewlog',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='transferapplication',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='transferapplication',
            name='reviewed_by',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=30, unique=True, verbose_name='申请编号')),
                ('transfer_unit', models.CharField(max_length=200, verbose_name='转移单位名称')),
                ('transfer_address', models.CharField(max_length=300, verbose_name='转移单位地址')),
                ('transfer_contact', models.CharField(max_length=50, verbose_name='转移联系人')),
                ('transfer_phone', models.CharField(max_length=20, verbose_name='转移联系电话')),
                ('receive_unit', models.CharField(max_length=200, verbose_name='接收单位名称')),
                ('receive_province', models.CharField(max_length=50, verbose_name='接收省份')),
                ('receive_address', models.CharField(max_length=300, verbose_name='接收单位地址')),
                ('receive_contact', models.CharField(max_length=50, verbose_name='接收联系人')),
                ('receive_phone', models.CharField(max_length=20, verbose_name='接收联系电话')),
                ('disposal_method', models.CharField(max_length=50, verbose_name='处置方式')),
                ('waste_name', models.CharField(max_length=200, verbose_name='废物名称')),
                ('waste_category', models.CharField(max_length=50, verbose_name='废物类别')),
                ('waste_code', models.CharField(max_length=50, verbose_name='废物代码')),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='转移数量（吨）')),
                ('waste_form', models.CharField(max_length=50, verbose_name='形态')),
                ('packaging', models.CharField(max_length=200, verbose_name='包装方式')),
                ('main_components', models.CharField(blank=True, default='', max_length=500, verbose_name='主要成分')),
                ('hazardous', models.CharField(blank=True, default='', max_length=500, verbose_name='危险特性')),
                ('transport_unit', models.CharField(max_length=200, verbose_name='运输单位')),
                ('transport_method', models.CharField(max_length=50, verbose_name='运输方式')),
                ('transfer_start', models.DateField(verbose_name='转移期限（起）')),
                ('transfer_end', models.DateField(verbose_name='转移期限（止）')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('reviewing', '审核中'), ('approved', '已通过'), ('rejected', '已驳回'), ('completed', '备案完成')], default='draft', max_length=20, verbose_name='状态')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '备案申请',
                'verbose_name_plural': '备案申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('passed', '预审通过'), ('failed', '预审不通过'), ('error', '处理异常')], default='pending', max_length=20, verbose_name='预审状态')),
                ('summary', models.TextField(blank=True, default='', verbose_name='预审摘要')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='评分（0-100）')),
                ('issues', models.JSONField(blank=True, default=list, verbose_name='发现的问题')),
                ('suggestions', models.JSONField(blank=True, default=list, verbose_name='修改建议')),
                ('raw_response', models.TextField(blank=True, default='', verbose_name='AI原始返回')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_review', to='gufei_beian.application', verbose_name='所属申请')),
            ],
            options={
                'verbose_name': 'AI预审',
                'verbose_name_plural': 'AI预审',
            },
        ),
        migrations.CreateModel(
            name='ApplicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('contract', '委托合同'), ('receiver_license', '接收方营业执照'), ('receiver_capacity', '接收方处置能力证明'), ('transporter_license', '运输方资质证明'), ('transporter_pledge', '运输方污染防治承诺书'), ('legal_id', '法人身份证明'), ('authorization', '授权委托书')], max_length=50, verbose_name='文件类型')),
                ('file', models.FileField(upload_to='applications/%Y/%m/', verbose_name='文件')),
                ('original_name', models.CharField(max_length=300, verbose_name='原始文件名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='gufei_beian.application', verbose_name='所属申请')),
            ],
            options={
                'verbose_name': '申请附件',
                'verbose_name_plural': '申请附件',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_code', models.CharField(max_length=18, unique=True, verbose_name='统一社会信用代码')),
                ('enterprise_name', models.CharField(max_length=200, verbose_name='企业名称')),
                ('region', models.CharField(max_length=50, verbose_name='所在地')),
                ('address', models.CharField(max_length=300, verbose_name='详细地址')),
                ('legal_person', models.CharField(max_length=50, verbose_name='法定代表人')),
                ('legal_person_id', models.CharField(max_length=18, verbose_name='法定代表人身份证号')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('active', '正常'), ('disabled', '已禁用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise', to=settings.AUTH_USER_MODEL, verbose_name='用户账号')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='gufei_beian.enterprise', verbose_name='申请企业'),
        ),
        migrations.DeleteModel(
            name='ApplicationDocument',
        ),
        migrations.DeleteModel(
            name='EnterpriseProfile',
        ),
        migrations.DeleteModel(
            name='ReviewLog',
        ),
        migrations.DeleteModel(
            name='TransferApplication',
        ),
    ]
